### ISSUE TITLE
Clear Versioning Required

### ISSUE THREAD

**Issue by RaphaelHerd** [aws-quickstart/quickstart-linux-bastion#13]
Hey,

please can you set explicit versions in the linux-bastion-master.template where you reference to the submodules?

In the file for
   "ParameterKey": "QSS3KeyPrefix",
   "ParameterValue": "linux/bastion/latest"

is set linux/latest. That relates to the fact that if you want to setup an environtment you end up using this

"https://${QSS3BucketName}.${S3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template",
url. If you want to setup this stack again in a few weeks you may be broken because the linux/bastion/latest submodules has changed.

I don't want to modify the AWS provided example. I just want to use it as it is.

Thanks.

**Comment by agamzn** [comment]
Context: I'm administratively cleaning up the issues in this repository. 

I can't speak to the CI/CD process of the team a year ago, but at this point the submodules go through an extensive CI/CD pipeline before the submodules are updated in the master branch. If those tests fail, the template won't be promoted into master. We prefer to have the submodules on the same playing field across all references, rather than split into multiple versions. 

With all of that said, we'd love to understand your use-case a bit better - and continue the dialogue.

**Comment by agamzn** [comment]
FYI: I'll be closing this out in a week unless the conversation continues.
