### ISSUE TITLE
Bastion AutoScaling fail

### ISSUE THREAD

**Issue by jitenjha11** [aws-quickstart/quickstart-linux-bastion#44]
When I am using my own S3 url and try to run quickstart confluence template that time bastion template autoscaling going to fail
![selection_001](https://user-images.githubusercontent.com/2167486/44536857-04b92c00-a71b-11e8-874b-1d7fb668ed86.png)
![selection_002](https://user-images.githubusercontent.com/2167486/44536858-04b92c00-a71b-11e8-9314-9184ede2e22b.png)
![selection_003](https://user-images.githubusercontent.com/2167486/44536859-0551c280-a71b-11e8-87c2-9839a1d9d815.png)
![selection_004](https://user-images.githubusercontent.com/2167486/44536860-0551c280-a71b-11e8-92b7-6ae47f2e6e13.png)
![screencapture-ap-southeast-2-console-aws-amazon-cloudformation-home-2018-08-21-13_26_37](https://user-images.githubusercontent.com/2167486/44536929-3205da00-a71b-11e8-8e98-68fbe0dd9998.png)
![screenshot-ap-southeast-2 console aws amazon com-2018 08 21-14-22-52](https://user-images.githubusercontent.com/2167486/44536931-3205da00-a71b-11e8-9ac0-199303ecb877.png)
![screenshot-ap-southeast-2 console aws amazon com-2018 08 21-14-23-19](https://user-images.githubusercontent.com/2167486/44536933-3205da00-a71b-11e8-99bf-aec0e8e0d066.png)
![screenshot-ap-southeast-2 console aws amazon com-2018 08 21-14-24-13](https://user-images.githubusercontent.com/2167486/44536934-329e7080-a71b-11e8-9665-282ad2353388.png)
![screenshot-ap-southeast-2 console aws amazon com-2018 08 21-14-24-40](https://user-images.githubusercontent.com/2167486/44536935-329e7080-a71b-11e8-9314-77ad346198f8.png)
![screenshot-ap-southeast-2 console aws amazon com-2018 08 21-14-25-05](https://user-images.githubusercontent.com/2167486/44536936-329e7080-a71b-11e8-9548-820e5a6307b6.png)
![screenshot-ap-southeast-2 console aws amazon com-2018 08 21-14-25-29](https://user-images.githubusercontent.com/2167486/44536937-329e7080-a71b-11e8-81cb-6a7925cff6e7.png)

**Comment by hierynomus** [comment]
We had the same error, it was due to the fact that the `QSS3KeyPrefix` was not correct, it did not end in a `/`, so the init script could not be found. Just submitted #50 for that.

**Comment by g-borgulya** [comment]
I had the very same issue: if I install use the quicklaunch template following the link in the AWS documentation, setting it up manually, then the it works nicely. But I have to put my system together with cloudformation, and I found no way to refer to this repo directly, so had to copy the assets to my own s3 bucket, which produced the same issue. I couldn't find any useful info about it: CloudTrail showed the problematic event, but without any hints where to look for the problem.

Neither did it work with using the `QSS3BucketName` and `QSS3KeyPrefix` parameters nor with `AlternativeInitializationScript` and `BastionBanner`, always had the same issue. But if I'm not setting the `QSS3BucketName` and `QSS3KeyPrefix` parameters at all, leaving it to use its defaults, then it seems to work without problems from CloudFormation as well. It means if the resources are not in my bucket but in the default, then it's working properly.

I suspect that it must be some permission problem, but I haven't had the capacity yet to look deeper.

**Comment by tianomagdaong** [comment]
Encountered the same issue when moving the resources to our own repo.

**Comment by vsnyc** [comment]
The original issue reported by @jitenjha11 happened due to an account limit for Elastic IP addresses as seen in the message: `The maximum number of addresses has been reached.`

When running the Quick Start from your own repo and S3 bucket, please follow these instructions in our [Contributor's guide](https://aws-quickstart.github.io/option1.html). We do include the [taskcat](https://aws-quickstart.github.io/taskcat/) test specification in the ci directory that you can use as a base. 

The steps in summary are:
1. Clone the repo
```
git clone --recurse-submodules git@github.com:aws-quickstart/quickstart-linux-bastion.git`
```
2. Change to the directory
```
cd quickstart-linux-bastion
```
3. Optional, make a copy of the original test spec files (or edit directly if you prefer)
```
cp ci/taskcat.yml ci/taskcat-local.yml
cp ci/linux-bastion-master-amznlinuxhvm.json ci/amzn-linux-params.json
```
4. Update the `amzn-linux-params.json` parameters file to match your environment, update the `taskcat-local.yml` file to narrow down the region and environment you are going to deploy the stack in; e.g., us-east-2 and Amazon Linux.
5. Run taskcat to deploy the stack
```
taskcat -c ci/taskcat-local.yml -n --enable-sig-v2
```

I have also uploaded a [screen recording](https://www.youtube.com/watch?v=KCdMlIezkUg) which should help. Please change the playback speed if the video is moving too fast, I dropped a lot of duplicate frames to reduce the size. 

Absent any environmental factors, the Quick Start should deploy successfully.

In the screen recording, you can see that I made [two changes](https://www.youtube.com/watch?v=KCdMlIezkUg&t=36s) in the `amzn-linux-params.json` file: The name of key pair, and IP address range from where I allow access. In taskcat-local.yml, I delete all the configurations except `amznlinuxhvm` and specify the region as `us-east-2`.

**Comment by vsnyc** [comment]
Closing as no outstanding questions remain.
